# Generated by Django 2.2.3 on 2019-07-13 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0003_category_cover_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='countUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_development.Category')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_development.api')),
            ],
        ),
    ]
