# Generated by Django 2.2.3 on 2019-07-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0004_countupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
