# Generated by Django 2.2.3 on 2019-07-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0005_api_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='count',
            new_name='counts',
        ),
    ]
