# Generated by Django 2.2.3 on 2019-07-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0006_auto_20190713_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='counts',
        ),
    ]
