# Generated by Django 2.2.3 on 2019-07-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0007_remove_api_counts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='countUpload',
        ),
    ]
