# Generated by Django 2.2.3 on 2019-07-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0008_delete_countupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wallpapers'),
        ),
    ]
