# Generated by Django 2.2.3 on 2019-07-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_development', '0009_api_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
